# combi configuration file
kind: json
global:
  rawConfig: ""
  conditions:
    mandatory: []
    optional: []
  actions:
    onSuccess: []
    onFailure: []
configs:
  example1:
    targetConfig: ./config/samples/json/target.json
    mergedConfig: ./config/samples/json/merged.json
    rawConfig: |
      {
        "list": [
          1, 2, 3
        ],
        "new_object": 4,
        "object": {
          "foo4": null,
          "foo5": 1,
          "foo6": "ss"
        }
      }

    conditions:
      mandatory:
      - name: "search new object value to check condition"
        template: |
          {{- $config := . -}}
          {{- printf "%.0f" $config.new_object -}}
        value: "4"
      - name: "search object foo4 value to check condition"
        template: |
          {{- $config := . -}}
          {{- if (eq $config.object.foo4 nil) -}}
            {{- printf "null" -}}
          {{- end -}}
        value: "null"
      optional: []

    actions:
      onSuccess:
      - name: "execute success message config action"
        command:
        - echo
        - -e
        - "success in config for you\n"
        script: ""
      onFailure:
      - name: "execute success message config action"
        command:
        - echo
        - -e
        - "fail in config for you\n"
        script: ""
