# combi configuration file
kind: libconfig
global:
  rawConfig: ""
  conditions:
    mandatory: []
    optional: []
  actions:
    onSuccess: []
    onFailure: []
configs:
  example1:
    targetConfig: ./config/samples/json/target.json
    mergedConfig: ./config/samples/json/merged.json
    rawConfig: |
      {}

    conditions:
      mandatory: []
      optional: []

    actions:
      onSuccess:
      - name: "execute success message config action"
        command:
        - echo
        - -e
        - "success in config for you\n"
        script: ""
      onFailure:
      - name: "execute success message config action"
        command:
        - echo
        - -e
        - "fail in config for you\n"
        script: ""
