# combi configuration file
kind: nginx
global:
  rawConfig: ""
  conditions:
    mandatory: []
    optional: []
  actions:
    onSuccess: []
    onFailure: []
configs:
  example1:
    targetConfig: ./config/samples/nginx/target.conf
    mergedConfig: ./config/samples/nginx/merged.conf
    rawConfig: |
      worker_processes  2;

      events {
          worker_connections   2000;

          use kqueue;
      }

      http {
          client_header_timeout  3m;
          client_body_timeout    3m;
          send_timeout           3m;

          client_header_buffer_size    1k;
          large_client_header_buffers  4 4k;

          server {
              access_log   /var/log/nginx.access_log  main;
              location / {
                  proxy_set_header   Host             $host;
                  proxy_set_header   X-Real-IP        $remote_addr;
              }
          }
      }

    conditions:
      mandatory:
      - name: "search new block value to check condition"
        template: |
          {{- $config := . -}}
          {{- printf "%s" $config.events.worker_connections -}}
        value: "2000"
      - name: "search value with param to check condition"
        template: |
          {{- $config := . -}}
          {{- printf "%s" (index $config.http.server "error_page[404]") -}}
        value: "/404.html"
      - name: "search new value in block to check condition"
        template: |
          {{- $config := . -}}
          {{- printf "%s" $config.http.server.listen -}}
        value: "one.example.com"
      - name: "search old value in block to check condition"
        template: |
          {{- $config := . -}}
          {{- printf "%s" (index $config.http.server "location[/]").proxy_pass -}}
        value: "http://127.0.0.1/"
      - name: "search new value in block to check condition"
        template: |
          {{- $config := . -}}
          {{- $location := (index $config.http.server "location[/]") -}}
          {{- printf "%s" (index $location "proxy_set_header[Host]") -}}
        value: "$host"
      optional: []

    actions:
      onSuccess:
      - name: "execute success message config action"
        command:
        - echo
        - -e
        - "success in config for you\n"
        script: ""
      onFailure:
      - name: "execute success message config action"
        command:
        - echo
        - -e
        - "fail in config for you\n"
        script: ""
