# combi configuration file
kind: "" # libconfig|json
global:
  rawConfig: ""
  conditions:
    mandatory: []
    optional: []
  actions:
    onSuccess: []
    onFailure: []
configs:
  example1:
    targetConfig: "" # path to the target file to merge the raw config
    mergedConfig: "" # path to the result file with the merged config
    rawConfig: "" # raw config to merge in target file

    conditions:
      mandatory: []
      # - name: ""
      #   template: ""
      #   value: ""
      optional: []
      # - name: ""
      #   template: ""
      #   value: ""

    actions:
      onSuccess: []
      # - name: ""
      #   command: []
      #   script: ""
      onFailure: []
      # - name: ""
      #   command: []
      #   script: ""
