# gcmerge configuration file
kind: libconfig
global:
  rawConfig: |
    array_test=
    [
      "item1", "item2", "item3",
    ]
  conditions:
    mandatory: []
    optional: []
  actions:
    onSuccess: []
    onFailure: []
configs:
  example1:
    targetConfig: ./config/samples/libconfig.cnf
    mergedConfig: ./config/samples/merged.cnf
    rawConfig: |
      datadir="/var/lib/proxysql"

      admin_variables=
      {
        admin_credentials="admin:admin;radmin:radmin"
        mysql_ifaces="0.0.0.0:6032"
      }

    conditions:
      mandatory:
      - name: "search primitive value to check condition"
        template: |
          {{- $config := .example1 -}}
          {{- range $i, $s := $config -}}
            {{- if (eq (index $config $i).SetingName "int64field") -}}
              {{- printf "%s" (index $config $i).SettingValue.Primitive.Value -}}
            {{- end -}}
          {{- end -}}
        value: "500L"
      - name: "search env variable to check condition"
        template: |
          {{- printf "%s" (env "MANDATORY_ENV_VAR") -}}
        value: "true"
      optional:
      - name: "print root primitive values condition"
        template: |
          {{- $config := .example1 -}}
          {{- range $i, $s := $config -}}
            {{- if (index $config $i).SettingValue.Primitive -}}
              {{- printf "%v" (index $config $i).SetingName -}}=
              {{- printf "%v\n" (index $config $i).SettingValue.Primitive.Value -}}
            {{- end -}}
          {{- end -}}
          {{- printf "----------------------------------------------------------------\n" -}}
        value: ""

    actions:
      onSuccess:
      - name: "execute success message config action"
        command:
        - echo
        - -e
        - "success in config for you\n"
        script: ""
      onFailure:
      - name: "execute success message config action"
        command:
        - echo
        - -e
        - "fail in config for you\n"
        script: ""

# maybe separate actions in success actions and failure actions
# necesito:
# - nombre del repo
# - token de acceso
# - owner del repo (a lo mejor)
# - path de la config en el repo
# - nombre de la configuración específica
