# gcmerge configuration file
kind: libconfig
global:
  rawConfig: |
    datadir="/var/lib/proxysql"
    
    admin_variables=
    {
      admin_credentials="admin:admin;radmin:radmin"
      mysql_ifaces="0.0.0.0:6032"
    }
  conditions:
  - name: condition1
    template: |
      {{- $config := . -}}
      {{- printf "%s" $config.metadata.name -}}
    value: ""
  actions:
  - name: action1
    command:
    - echo
    - -e
    - "success in global for you\n"
    script: |
      #!/usr/bin/env bash
      echo -e "success"
configs:
  example1:
    targetConfig: ./config/samples/libconfig.cnf
    mergedConfig: ./config/samples/merged.cnf
    rawConfig: |
      datadir="/var/lib/proxysql"
      
      array_test=
      [
        "item1", "item2", "item3",
      ]

      admin_variables=
      {
        admin_credentials="admin:admin;radmin:radmin"
        mysql_ifaces="0.0.0.0:6032"
      }

    conditions:
    - name: condition1
      template: |
        {{- $config := . -}}
        {{- printf "%s" $config.metadata.name -}}
      value: ""

    actions:
    - name: action1
      command:
      - echo
      - -e
      - "success in config for you\n"
      script: |
        #!/usr/bin/env bash
        echo -e "success"

# maybe separate actions in success actions and failure actions
# necesito:
# - nombre del repo
# - token de acceso
# - owner del repo (a lo mejor)
# - path de la config en el repo
# - nombre de la configuración específica
