apiVersion: v1
kind: Secret
metadata:
  name: source
type: Opaque
stringData:
  config.cnf: |
    datadir="/var/lib/proxysql"

    admin_variables=
    {
      admin_credentials="admin:admin;radmin:radmin"
      mysql_ifaces="0.0.0.0:6032"
    }
